<?php

namespace IB\SondageBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * SondageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SondageRepository extends EntityRepository
{
	public function getSondages()
	{
			$sondage = $this->createQueryBuilder('s')
			             	->leftJoin('s.voteIpAdress', 'i')
              				->addSelect('i')
              				->innerJoin('s.reponses', 'r')
              				->addSelect('r')
							->orderBy('s.date', 'DESC');		
			return $sondage->getQuery()
				   		   ->getResult();
	}

	public function getLastSondage()
	{
		$q = $this->_em->createQuery( 'SELECT s FROM IBSondageBundle:Sondage s ORDER BY s.date DESC' ); 
		$q->setMaxResults(1);

		$ids = $q->getArrayResult();

		$q = $this->_em->createQuery( 'SELECT s, r, i FROM IBSondageBundle:Sondage s LEFT JOIN s.voteIpAdress i INNER JOIN s.reponses r WHERE s.id IN (:ids) ORDER BY s.date DESC' ); 
		$q->setParameter('ids', $ids); 

        $sondage = $q->getOneOrNullResult(); 

        return $sondage;
	}
}