imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: sonata/sonata_core.yml }
    - { resource: sonata/sonata_config.yml }

framework:
    http_method_override: true
    translator:      { fallback: %locale% }
    secret:          %secret%
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: %kernel.debug%
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_proxies: ~
    session:         ~
    fragments:       ~

# Twig Configuration
twig:
    exception_controller: 'FOS\RestBundle\Controller\ExceptionController::showAction'
    debug:            %kernel.debug%
    strict_variables: %kernel.debug%
    globals:
        contact_me_mail: %mailer_user%
        title_website: IB
    form:
        resources:
            - 'SonataFormatterBundle:Form:formatter.html.twig'

# Assetic Configuration
assetic:
    debug:          %kernel.debug%
    use_controller: false
    bundles:        ['IBCommentaireBundle', 'IBArticleBundle', 'IBSchemaBundle', 'IBLikeBundle', 'IBPageBundle']
    #java: /usr/bin/java
    filters:
        less:
            node: /usr/local/bin/node
            node_paths: [usr/local/lib/node_modules]
            apply_to: "\.less$"
        cssrewrite: ~
        sass:
            bin: /usr/bin/sass
            apply_to: "\.sass$"
        scss:
            sass: /usr/bin/sass
            apply_to: "\.scss$" 
        compass:
            sass: /usr/bin/compass
            apply_to: "\.(scss|sass)$" 
        yui_css:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"
        yui_js:
            jar: "%kernel.root_dir%/Resources/java/yuicompressor.jar"

doctrine:
    dbal:
        driver:   %database_driver%
        host:     %database_host%
        port:     %database_port%
        dbname:   %database_name%
        user:     %database_user%
        password: %database_password%
        charset:  UTF8
        types:
            json: Sonata\Doctrine\Types\JsonType
    orm:
        auto_generate_proxy_classes: %kernel.debug%
        entity_managers:
            default:
                auto-mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter

swiftmailer:
    transport: %mailer_transport%
    host:      %mailer_host%
    username:  %mailer_user%
    password:  %mailer_password%
    spool:     { type: memory }

fos_user:
    db_driver: orm
    firewall_name: main
    user_class: IB\UserBundle\Entity\User
    group:
        group_class: IB\UserBundle\Entity\Group
    profile:
        form:
            type:               fos_user_profile
            handler:            fos_user.profile.form.handler.default
            name:               fos_user_profile_form
            validation_groups:  [Authentication]
    registration:
        confirmation:
            enabled: true

fos_rest:
    view:
        jsonp_handler: ~
        formats:
            json: true
            html: true
            rss: false
            xml: false
    access_denied_listener:
        json: true

fos_js_routing:
    routes_to_expose: "api_*"

knp_paginator:
    page_range: 5
    default_options:
        page_name: page
        sort_field_name: sort
        sort_direction_name: direction
        distinct: true
    template:
        pagination: KnpPaginatorBundle:Pagination:sliding.html.twig
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig

stof_doctrine_extensions:
    orm:
        default:
            tree: true
            sluggable: true
            timestampable: true
            uploadable: false
            softdeleteable: true

ib_like:
    entities:
        - 'IB\ArticleBundle\Entity\Article'

ib_commentaire:
    entities:
        - 'IB\ArticleBundle\Entity\Article'