parameters:
   ib_article.per_page: 5
   ib_article.limit_list: 3

services:
#    ib_article.example:
#        class: %ib_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
